baseURL = "https://deadpanpoetry.org/"
languageCode = "en-us"
title = "Deadpan Poetry"

[params]
  # Uncomment and set the path if you have a header image:
  header_image = "/images/header2.jpg" 

[frontmatter]
default = "yaml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[mediaTypes."application/rss+xml"]
  suffixes = ["xml"]

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "index"
  isPlainText = false
  notAlternative = true  